# Generated by Django 3.2.6 on 2021-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='book_category',
            field=models.ManyToManyField(blank=True, to='bookmark.Book_Category'),
        ),
    ]
