# Generated by Django 3.2.6 on 2021-08-13 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jamjamapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=20, null=True, unique=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(default='010', max_length=11, null=True)),
                ('birthyear', models.CharField(max_length=4, null=True)),
                ('birthmonth', models.CharField(max_length=2, null=True)),
                ('birthday', models.CharField(max_length=2, null=True)),
                ('gender', models.IntegerField(choices=[(1, '성별'), (2, '남성'), (3, '여성')], default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', jamjamapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Big_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Writer', models.CharField(max_length=100)),
                ('Write_day', models.DateTimeField(verbose_name='date published')),
                ('Content', models.TextField()),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('view_count', models.IntegerField(default=0)),
                ('Blog_likes', models.ManyToManyField(related_name='Blog_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_site_name', models.CharField(max_length=50)),
                ('book_url', models.URLField()),
            ],
            options={
                'ordering': ['book_site_name'],
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_title', models.CharField(max_length=100)),
                ('bucket_date', models.CharField(default='oooo년 oo월 oo일', max_length=15)),
                ('bucket_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=100)),
                ('diary_date', models.CharField(default='oooo년 oo월 oo일', max_length=15)),
                ('diary_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Small_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Play_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Writer', models.CharField(max_length=100)),
                ('Write_day', models.DateTimeField(verbose_name='date published')),
                ('Content', models.TextField()),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('view_count', models.IntegerField(default=0)),
                ('big_region', models.ManyToManyField(blank=True, to='jamjamapp.Big_Region')),
                ('play_likes', models.ManyToManyField(related_name='Play_likes', to=settings.AUTH_USER_MODEL)),
                ('small_region', models.ManyToManyField(blank=True, to='jamjamapp.Small_Region')),
            ],
        ),
        migrations.CreateModel(
            name='Look_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Writer', models.CharField(max_length=100)),
                ('Write_day', models.DateTimeField(verbose_name='date published')),
                ('Content', models.TextField()),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('view_count', models.IntegerField(default=0)),
                ('Look_likes', models.ManyToManyField(related_name='Look_likes', to=settings.AUTH_USER_MODEL)),
                ('big_region', models.ManyToManyField(blank=True, to='jamjamapp.Big_Region')),
                ('small_region', models.ManyToManyField(blank=True, to='jamjamapp.Small_Region')),
            ],
        ),
        migrations.CreateModel(
            name='Eat_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Writer', models.CharField(max_length=100)),
                ('Write_day', models.DateTimeField(verbose_name='date published')),
                ('Content', models.TextField()),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('view_count', models.IntegerField(default=0)),
                ('Eat_likes', models.ManyToManyField(related_name='Eat_likes', to=settings.AUTH_USER_MODEL)),
                ('big_region', models.ManyToManyField(blank=True, to='jamjamapp.Big_Region')),
                ('small_region', models.ManyToManyField(blank=True, to='jamjamapp.Small_Region')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jamjamapp.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='jamjamapp.Hashtag'),
        ),
    ]
