# Generated by Django 3.2.6 on 2021-11-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamjamapp', '0004_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
    ]
